# Generated by Django 6.0.4 on 2026-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_contacto', models.CharField(blank=True, max_length=150)),
                ('clave_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('emisor_nombre', models.CharField(max_length=150)),
                ('emisor_ci', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('trimestral', 'Trimestral (90 días)'), ('semestral', 'Semestral (180 días)'), ('perpetua', 'Perpetua')], max_length=15)),
                ('nonce', models.CharField(db_index=True, max_length=36, unique=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(db_index=True, default=False)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_desactivacion', models.CharField(blank=True, max_length=200)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['-creada_en'],
            },
        ),
    ]
