# Generated by Django 6.0.4 on 2026-05-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('compra', 'Compra a proveedor'), ('venta', 'Venta'), ('ajuste', 'Ajuste de inventario'), ('merma', 'Merma/Pérdida'), ('devolucion', 'Devolución')], max_length=50)),
                ('referencia_id', models.PositiveIntegerField(blank=True, help_text='ID de orden o venta asociada', null=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento Stock',
                'verbose_name_plural': 'Movimientos Stock',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', '-fecha'], name='inventario__product_082fec_idx'), models.Index(fields=['motivo', '-fecha'], name='inventario__motivo_4171bb_idx')],
            },
        ),
    ]
