# Generated by Django 6.0.4 on 2026-05-03 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detalleventa',
            name='ventas_deta_id_prod_341ee9_idx',
        ),
        migrations.AddField(
            model_name='venta',
            name='cajero_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cajero', '-fecha_venta'], name='ventas_vent_cajero_034df3_idx'),
        ),
    ]
