# Generated by Django 6.0.4 on 2026-05-05 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_detalleventa_ventas_deta_id_prod_341ee9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.TextField(blank=True, default='')),
                ('rnc', models.CharField(blank=True, default='', max_length=50)),
                ('notas', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='ventas_clie_nombre_134519_idx'), models.Index(fields=['telefono'], name='ventas_clie_telefon_573c09_idx')],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cliente'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', '-fecha_venta'], name='ventas_vent_cliente_d1b972_idx'),
        ),
    ]
