# Generated by Django 6.0.4 on 2026-05-05 01:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_cliente_venta_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Mi Negocio', max_length=150, verbose_name='Nombre del Negocio')),
                ('rnc_negocio', models.CharField(blank=True, default='', max_length=50, verbose_name='RNC del Negocio')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('simbolo_moneda', models.CharField(default='RD$', max_length=5, verbose_name='Simbolo de Moneda')),
                ('tasa_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('mensaje_recibo_superior', models.TextField(blank=True, default='', help_text='Texto que aparece arriba del recibo', verbose_name='Mensaje Recibo (superior)')),
                ('mensaje_recibo_inferior', models.TextField(blank=True, default='', help_text='Texto que aparece abajo del recibo', verbose_name='Mensaje Recibo (inferior)')),
                ('pie_pagina', models.CharField(blank=True, default='Gracias por su compra', max_length=200, verbose_name='Pie de pagina')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del Negocio')),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del Sistema',
                'verbose_name_plural': 'Configuracion del Sistema',
            },
        ),
    ]
