# Generated by Django 6.0.4 on 2026-05-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_actual', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('umbral_demanda_alta', models.IntegerField(default=30, help_text='Ventas en 24h que activan incremento')),
                ('incremento_por_demanda', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('imagen', models.ImageField(upload_to='recetas/')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto Final',
                'verbose_name_plural': 'Productos Finales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('razon', models.CharField(choices=[('demanda', 'Demanda alta'), ('manual', 'Ajuste manual')], max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='recetas.productofinal')),
            ],
            options={
                'verbose_name': 'Historial Precio',
                'verbose_name_plural': 'Historial Precios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_final', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='recetas.productofinal')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, help_text='Cantidad de insumo necesaria por unidad del producto final', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Detalle Receta',
                'verbose_name_plural': 'Detalles Receta',
                'unique_together': {('receta', 'producto')},
            },
        ),
    ]
