# Generated by Django 6.0.4 on 2026-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='rol',
            field=models.CharField(choices=[('cajero', 'Cajero'), ('administrador', 'Administrador'), ('superadmin', 'Superadmin')], default='cajero', max_length=20),
        ),
    ]
