# Generated by Django 6.0.4 on 2026-05-02 13:40

from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    """Crea los grupos de usuarios con sus permisos"""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Grupo: Cajero
    cajero_group, _ = Group.objects.get_or_create(name="Cajero")
    cajero_perms = Permission.objects.filter(
        codename__in=[
            "add_orden",
            "change_orden",
            "view_orden",
            "delete_orden",
            "add_venta",
            "view_venta",
            "view_productofinal",
        ]
    )
    cajero_group.permissions.set(cajero_perms)

    # Grupo: Chef
    chef_group, _ = Group.objects.get_or_create(name="Chef")
    chef_perms = Permission.objects.filter(
        codename__in=["add_productofinal", "change_productofinal", "delete_productofinal", "view_productofinal"]
    )
    chef_group.permissions.set(chef_perms)

    # Grupo: Administrador
    admin_group, _ = Group.objects.get_or_create(name="Administrador")
    admin_perms = Permission.objects.filter(
        content_type__app_label__in=["productos", "inventario", "recetas", "ordenes", "ventas"]
    )
    admin_group.permissions.set(admin_perms)

    # Grupo: Superadmin (todos los permisos)
    superadmin_group, _ = Group.objects.get_or_create(name="Superadmin")
    all_perms = Permission.objects.all()
    superadmin_group.permissions.set(all_perms)


def reverse_create_groups(apps, schema_editor):
    """Elimina los grupos creados"""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Cajero", "Chef", "Administrador", "Superadmin"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ordenes', '0001_initial'),
        ('ventas', '0001_initial'),
        ('recetas', '0001_initial'),
        ('productos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, reverse_create_groups),
    ]
