"""
Django settings for Inventory_Sales project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables helper
def env(key, default=None, cast=None):
    value = os.environ.get(key, default)
    if value is None:
        return None
    if cast == bool:
        if isinstance(value, bool):
            return value
        return str(value).lower() in ('true', '1', 'yes')
    if cast == int:
        return int(value)
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    import sys
    import warnings
    if not env('DJANGO_ALLOW_DEBUG_FALLBACK', False, cast=bool):
        raise RuntimeError(
            "DJANGO_SECRET_KEY no configurada. Configure la variable de entorno antes de iniciar."
        )
    warnings.warn("Usando SECRET_KEY inseguro de fallback. Solo para desarrollo.", RuntimeWarning)
    SECRET_KEY = 'django-insecure--y9j3lam)@cw=g8o2foviuh3)kt@)vjity7lfgt)0g+ib@q^!9'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG se fuerza a False si hay LICENSE_SECRET configurada (produccion)
_DEBUG_DEFAULT = False
if env('LICENSE_SECRET', ''):
    _DEBUG_DEFAULT = False  # Forzar DEBUG=False en produccion
DEBUG = env('DJANGO_DEBUG', _DEBUG_DEFAULT, cast=bool)

# Si DEBUG=True en produccion, advertir y forzar False
if DEBUG and env('LICENSE_SECRET', ''):
    import warnings
    warnings.warn(
        "DEBUG=True detectado con LICENSE_SECRET configurada. "
        "Forzando DEBUG=False para proteger secretos. "
        "Use DJANGO_DEBUG=True explicitamente solo para desarrollo.",
        RuntimeWarning
    )
    DEBUG = False

ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://void-delta-tidal.ngrok-free.dev',
]
if ngrok_http := env('DJANGO_CSRF_NGROK_HTTP'):
    CSRF_TRUSTED_ORIGINS.extend(ngrok_http.split(','))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'axes',
    # Custom apps
    'productos',
    'inventario',
    'ventas',
    'reportes',
    'usuarios',
    'licencias',
]

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'licencias.middleware.LicenseMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Inventory_Sales.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ventas.context_processors.configuracion_sistema',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventory_Sales.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import re
from urllib.parse import urlparse, unquote

_db_url = env('DATABASE_URL', '')
if _db_url:
    parsed = urlparse(_db_url)
    if parsed.scheme and parsed.hostname:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote(parsed.path.lstrip('/')),
                'USER': unquote(parsed.username) if parsed.username else '',
                'PASSWORD': unquote(parsed.password) if parsed.password else '',
                'HOST': parsed.hostname,
                'PORT': parsed.port or '5432',
                'OPTIONS': {},
            }
        }
        if parsed.query and 'sslmode=require' in parsed.query:
            DATABASES['default']['OPTIONS']['sslmode'] = 'require'
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': _db_url.rsplit('/', 1)[-1],
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': env('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': env('DB_NAME', 'inventory_sales'),
            'USER': env('DB_USER', 'postgres'),
            'PASSWORD': env('DB_PASSWORD', 'postgres'),
            'HOST': env('DB_HOST', 'localhost'),
            'PORT': env('DB_PORT', '5432'),
        }
    }

# Authentication settings
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Brute force protection (django-axes)
AXES_ENABLED = env('AXES_ENABLED', True, cast=bool)
AXES_FAILURE_LIMIT = env('AXES_FAILURE_LIMIT', 5, cast=int)
from datetime import timedelta

_AXES_HOURS = env('AXES_COOLOFF_TIME', default=1, cast=int)
AXES_COOLOFF_TIME = timedelta(hours=_AXES_HOURS)
AXES_LOCKOUT_TEMPLATE = None  # Uses default login with error
AXES_RESET_ON_SUCCESS = True
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Session security
SESSION_COOKIE_AGE = env('SESSION_COOKIE_AGE', 3600, cast=int)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': BASE_DIR / 'media',
            'base_url': '/media/',
        },
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.StaticFilesStorage',
    },
}

# Media files configuration
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = env('DATA_UPLOAD_MAX_MEMORY_SIZE', 5 * 1024 * 1024, cast=int)  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Security settings (production-ready, enabled via env)
SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT', False, cast=bool)
SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE', False, cast=bool)
CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE', False, cast=bool)
SESSION_COOKIE_HTTPONLY = env('SESSION_COOKIE_HTTPONLY', True, cast=bool)
CSRF_COOKIE_HTTPONLY = env('CSRF_COOKIE_HTTPONLY', True, cast=bool)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = env('SECURE_HSTS_SECONDS', 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env('SECURE_HSTS_INCLUDE_SUBDOMAINS', False, cast=bool)
SECURE_HSTS_PRELOAD = env('SECURE_HSTS_PRELOAD', False, cast=bool)
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# License key for validation (MUST match KeyManagement LICENSE_SECRET)
LICENSE_SECRET = env('LICENSE_SECRET', '')

# Content Security Policy (basic, opt-in via env)
CONTENT_SECURITY_POLICY = env('CONTENT_SECURITY_POLICY', None)
if CONTENT_SECURITY_POLICY:
    # Use django-csp or middleware; here we set a simple header via middleware
    pass


# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ventas': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'inventario': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
