# Generated by Django 6.0.4 on 2026-05-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(help_text='Teléfono o email', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('insumo', 'Insumo'), ('final', 'Producto Final'), ('ambos', 'Ambos')], default='ambos', max_length=10)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='productos.categoria', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_producto', models.CharField(choices=[('insumo', 'Insumo'), ('final', 'Producto Final')], default='insumo', max_length=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('unidad', 'Unidad'), ('paquete', 'Paquete')], max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('umbral_demanda_alta', models.IntegerField(blank=True, help_text='Ventas en 24h que activan incremento', null=True)),
                ('incremento_por_demanda', models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=5, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', to='productos.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.proveedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
