# Generated by Django 6.0.4 on 2026-05-03 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='incremento_por_demanda',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='umbral_demanda_alta',
        ),
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria', verbose_name='Categoria padre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase Font Awesome, ej: fa-soap', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramos'), ('g', 'Gramos'), ('litro', 'Litros'), ('ml', 'Mililitros'), ('paquete', 'Paquete'), ('caja', 'Caja')], default='unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(help_text='Telefono o email', max_length=150),
        ),
    ]
