# Generated by Django 6.0.4 on 2026-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=100)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En preparación'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['numero_orden'], name='ordenes_ord_numero__fd8b83_idx'), models.Index(fields=['estado', '-fecha_hora'], name='ordenes_ord_estado_6620b4_idx')],
            },
        ),
    ]
